/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smegi.bonusi;

import com.smegi.bonusi.model.Database;
import com.smegi.bonusi.model.Excel;
import com.smegi.bonusi.model.User;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergej
 */
public class Bonusi extends javax.swing.JFrame {

    /**
     * Creates new form Bonusi
     */
    public Bonusi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_north = new javax.swing.JPanel();
        label_bonusi = new javax.swing.JLabel();
        button_refresh = new javax.swing.JButton();
        scrollpane_table = new javax.swing.JScrollPane();
        table_mainTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        panel_north.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 50, 5, 50));
        panel_north.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        label_bonusi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_bonusi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bonusi.setText("Bonusi");
        panel_north.add(label_bonusi);

        button_refresh.setText("Refresh");
        panel_north.add(button_refresh);

        getContentPane().add(panel_north, java.awt.BorderLayout.NORTH);

        table_mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpane_table.setViewportView(table_mainTable);

        getContentPane().add(scrollpane_table, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonusi().setVisible(true);

                Database db = new Database();
                List<User> ul = db.getUsersList();
                for (User user : ul) {
                 //   System.out.println(user.getId() + " Username: " + user.getName() + " Paid: " + user.getTotalPaymentsForCurrentYear());
                }

                Excel excel = new Excel(ul);
                excel.getExcelBonuses(9);
                
                DefaultTableModel model = (DefaultTableModel) table_mainTable.getModel();
                model.addRow(new Object[]{"asdf", 12, 15});

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_refresh;
    private javax.swing.JLabel label_bonusi;
    private javax.swing.JPanel panel_north;
    private javax.swing.JScrollPane scrollpane_table;
    private javax.swing.JTable table_mainTable;
    // End of variables declaration//GEN-END:variables
}
